name: monet-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.8
  - cartopy
  - dask
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pip
  - pydecorate
  - seaborn
  - xarray
  - pytest
  - pytest-cov
  - pooch
  - python-stratify
  - pip:
    - monet-regrid @ git+https://github.com/noaa-oar-arl/monet-regrid
    - monet-stats @ git+https://github.com/noaa-oar-arl/monet-stats