name: monet-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.8
  - cartopy
  - dask
  - matplotlib
  - monet-regrid
  - netcdf4
  - numpy
  - pandas
  - pip
  - pydecorate
  - seaborn
  - xarray
