name: monet-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.8
  - cartopy
  - dask
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pip
  - pydecorate
  - seaborn
  - xarray
  - pytest
  - pytest-cov
  - pooch
  - esmpy
  - mpi4py
  - pip:
      - global-land-mask
      - xregrid @ git+https://github.com/bbakernoaa/xregrid
      - pytspack @ git+https://github.com/noaa-oar-arl/pytspack
      - monet-stats @ git+https://github.com/noaa-oar-arl/monet-stats
