{% set name = "monet" %}
{% set version = "2.1.10" %}

package:
  name: monet
  version: {{ version }}

source:
  git_url: https://github.com/noaa-oar-arl/MONET.git
  git_tag: develop
  #url: https://github.com/noaa-oar-arl/MONET/archive/v2.1.3-dev.2.tar.gz
  # sha256: 7027a0478cab0f877ebc7e412a0249d0578c0944fab4da6f341175995b957931

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} setup.py install"

requirements:
  build:
    - {{ compiler('c') }}
    - numpy
    - scipy
    - pandas
    - xarray
    - dask
    - cartopy
    - matplotlib
    - seaborn
    - pseudonetcdf
    - pyresample
    - xesmf # [not win]
    - python-stratify
    - pytables
  host:
    - git
    - python
  run:
    - python

about:
  home: https://monet-arl.readthedocs.io
  license: MIT License
  license_family: MIT
  license_file: LICENSE
  summary: The Model and ObservatioN Evaluation Tool - for meteorology and AQ

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - bbakernoaa
