name: monet-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - ipykernel
  - ipython
  #
  # core
  - cartopy
  - dask
  - matplotlib
  - netcdf4
  - numpy
  - pandas>=1.0
  - pillow>=9.1.0
  - seaborn
  - xarray
  - esmpy
  #
  #
  - pip>=21.1
  - pip:
      - mkdocs
      - mkdocs-material
      - mkdocstrings[python]
      - mkdocs-gallery
      - "-e ../"
